export const prompts: string[] = [
  "You left your laptop open and your friend emails your boss. What's the email?",
  "Turkey ate my ______!",
  "The person closest to the TV got you a gift - it's a _______",
  "Knock knock knock, ______ is at the door",
  "Frog had a rough day at Sobotec, and ordered _______ on UberEats",
  "Clap clap clap on a poodles fat _____",
  "You ordered a burger and accidentally got this as a condiment",
  "You're spending a night at the Millards, but the beds are full. You just found a place to sleep. Where is it?",
  "Zoonie calls you to tell you about his day. What happened?",
  "Fil watched a new documentary. What lifestyle changes is he making?",
  "Doni got a new dog. What does Fil call it?",
  "Chedo's calling - he needs Frog to ______",
  "Mobins Hungry! He ate all of Gilly's _____",
  "Bean has a hot new business idea: ________",
  "Frog has a new stock shill - the company sells ________",
  "Scientists have discovered a new way to ingest nicotene. Instead of Zyn's, Zoonie is taking nicotene by ______",
  "Frogs oura ring says too much  _______ is disturbing his sleep",
  "Abby switched departments at work. She's now taking care of _______",
  "Patty is back from retirement. She just asked Gilly to _______",
  "Brazilians have discovered a hot new skincare routine. They're putting ______ on their faces",
  "Fils donating to a new charity. It's called _______",
  "The person sitting furthest on the left started calling their significant other ______",
  "The person on the right just got fired. What do you say to them?",
  "The person farthest from the tv got arrested. What for?",
];
